-- ============================================
-- BANCO DE DADOS - PROJETO KFKA
-- CRIAÇÃO DAS TABELAS
-- ============================================

-- 1. TURMA
CREATE TABLE TURMA (
    ID_TURMA NUMBER(4) CONSTRAINT PK_TURMA PRIMARY KEY,
    NOME VARCHAR2(50) NOT NULL,
    ANO_LETIVO NUMBER(4) NOT NULL,
    SERIE VARCHAR2(30) NOT NULL
);


-- 2. PROFESSOR
CREATE TABLE PROFESSOR (
    ID_PROFESSOR NUMBER(4) CONSTRAINT PK_PROFESSOR PRIMARY KEY,
    NOME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(100) NOT NULL
);


-- 3. DISCIPLINA
CREATE TABLE DISCIPLINA (
    ID_DISCIPLINA NUMBER(4) CONSTRAINT PK_DISCIPLINA PRIMARY KEY,
    NOME VARCHAR2(50) NOT NULL
);


-- 4. BIMESTRE
CREATE TABLE BIMESTRE (
    ID_BIMESTRE NUMBER(4) CONSTRAINT PK_BIMESTRE PRIMARY KEY,
    NUMERO NUMBER(1) NOT NULL,
    ANO_LETIVO NUMBER(4) NOT NULL
);


-- 5. ALUNO
CREATE TABLE ALUNO (
    ID_ALUNO NUMBER(4) CONSTRAINT PK_ALUNO PRIMARY KEY,
    NOME VARCHAR2(100) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL,
    EMAIL VARCHAR2(100),
    ID_TURMA NUMBER(4) NOT NULL,

    CONSTRAINT FK_ALUNO_TURMA
        FOREIGN KEY (ID_TURMA)
        REFERENCES TURMA(ID_TURMA)
);


-- 6. ACOMPANHAMENTO
CREATE TABLE ACOMPANHAMENTO (
    ID_ACOMPANHAMENTO NUMBER(4)
        CONSTRAINT PK_ACOMPANHAMENTO PRIMARY KEY,

    ID_ALUNO NUMBER(4) NOT NULL,

    ID_PROFESSOR NUMBER(4) NOT NULL,

    ID_DISCIPLINA NUMBER(4) NOT NULL,

    ID_BIMESTRE NUMBER(4) NOT NULL,

    MEDIA NUMBER(4,2),

    STATUS VARCHAR2(20) NOT NULL,

    OBSERVACAO VARCHAR2(500),

    CONSTRAINT FK_ACOMP_ALUNO
        FOREIGN KEY (ID_ALUNO)
        REFERENCES ALUNO(ID_ALUNO),

    CONSTRAINT FK_ACOMP_PROFESSOR
        FOREIGN KEY (ID_PROFESSOR)
        REFERENCES PROFESSOR(ID_PROFESSOR),

    CONSTRAINT FK_ACOMP_DISCIPLINA
        FOREIGN KEY (ID_DISCIPLINA)
        REFERENCES DISCIPLINA(ID_DISCIPLINA),

    CONSTRAINT FK_ACOMP_BIMESTRE
        FOREIGN KEY (ID_BIMESTRE)
        REFERENCES BIMESTRE(ID_BIMESTRE)
);


ALTER TABLE ACOMPANHAMENTO
ADD CONSTRAINT CK_ACOMP_MEDIA
CHECK (MEDIA BETWEEN 0 AND 10);

ALTER TABLE BIMESTRE
ADD CONSTRAINT CK_BIMESTRE_NUMERO
CHECK (NUMERO BETWEEN 1 AND 4);

ALTER TABLE ACOMPANHAMENTO
ADD CONSTRAINT CK_ACOMP_STATUS
CHECK (STATUS IN ('APROVADO', 'RECUPERACAO', 'REPROVADO'));


-- ============================================
-- SEQUENCES
-- ============================================

CREATE SEQUENCE SEQ_TURMA
START WITH 1
INCREMENT BY 1
MAXVALUE 9999;

CREATE SEQUENCE SEQ_PROFESSOR
START WITH 1
INCREMENT BY 1
MAXVALUE 9999;

CREATE SEQUENCE SEQ_DISCIPLINA
START WITH 1
INCREMENT BY 1
MAXVALUE 9999;

CREATE SEQUENCE SEQ_BIMESTRE
START WITH 1
INCREMENT BY 1
MAXVALUE 9999;

CREATE SEQUENCE SEQ_ALUNO
START WITH 1
INCREMENT BY 1
MAXVALUE 9999;

CREATE SEQUENCE SEQ_ACOMPANHAMENTO
START WITH 1
INCREMENT BY 1
MAXVALUE 9999;


-- ============================================
-- TURMAS
-- ============================================

INSERT INTO TURMA
(ID_TURMA, NOME, ANO_LETIVO, SERIE)
VALUES
(SEQ_TURMA.NEXTVAL, '6A', 2026, '6º Ano');

INSERT INTO TURMA
(ID_TURMA, NOME, ANO_LETIVO, SERIE)
VALUES
(SEQ_TURMA.NEXTVAL, '6B', 2026, '6º Ano');

INSERT INTO TURMA
(ID_TURMA, NOME, ANO_LETIVO, SERIE)
VALUES
(SEQ_TURMA.NEXTVAL, '7A', 2026, '7º Ano');

INSERT INTO TURMA
(ID_TURMA, NOME, ANO_LETIVO, SERIE)
VALUES
(SEQ_TURMA.NEXTVAL, '8A', 2026, '8º Ano');

INSERT INTO TURMA
(ID_TURMA, NOME, ANO_LETIVO, SERIE)
VALUES
(SEQ_TURMA.NEXTVAL, '9A', 2026, '9º Ano');


 -- ============================================
-- PROFESSORES
-- ============================================

INSERT INTO PROFESSOR
(ID_PROFESSOR, NOME, EMAIL)
VALUES
(SEQ_PROFESSOR.NEXTVAL, 'Carlos Souza', 'carlos.souza@escola.com');

INSERT INTO PROFESSOR
(ID_PROFESSOR, NOME, EMAIL)
VALUES
(SEQ_PROFESSOR.NEXTVAL, 'Ana Oliveira', 'ana.oliveira@escola.com');

INSERT INTO PROFESSOR
(ID_PROFESSOR, NOME, EMAIL)
VALUES
(SEQ_PROFESSOR.NEXTVAL, 'Marcos Santos', 'marcos.santos@escola.com');

INSERT INTO PROFESSOR
(ID_PROFESSOR, NOME, EMAIL)
VALUES
(SEQ_PROFESSOR.NEXTVAL, 'Juliana Costa', 'juliana.costa@escola.com');

INSERT INTO PROFESSOR
(ID_PROFESSOR, NOME, EMAIL)
VALUES
(SEQ_PROFESSOR.NEXTVAL, 'Rafael Lima', 'rafael.lima@escola.com');


-- ============================================
-- DISCIPLINAS
-- ============================================

INSERT INTO DISCIPLINA
(ID_DISCIPLINA, NOME)
VALUES
(SEQ_DISCIPLINA.NEXTVAL, 'Matemática');

INSERT INTO DISCIPLINA
(ID_DISCIPLINA, NOME)
VALUES
(SEQ_DISCIPLINA.NEXTVAL, 'Português');

INSERT INTO DISCIPLINA
(ID_DISCIPLINA, NOME)
VALUES
(SEQ_DISCIPLINA.NEXTVAL, 'História');

INSERT INTO DISCIPLINA
(ID_DISCIPLINA, NOME)
VALUES
(SEQ_DISCIPLINA.NEXTVAL, 'Ciências');

INSERT INTO DISCIPLINA
(ID_DISCIPLINA, NOME)
VALUES
(SEQ_DISCIPLINA.NEXTVAL, 'Geografia');



-- ============================================
-- BIMESTRES
-- ============================================

INSERT INTO BIMESTRE
(ID_BIMESTRE, NUMERO, ANO_LETIVO)
VALUES
(SEQ_BIMESTRE.NEXTVAL, 1, 2026);

INSERT INTO BIMESTRE
(ID_BIMESTRE, NUMERO, ANO_LETIVO)
VALUES
(SEQ_BIMESTRE.NEXTVAL, 2, 2026);

INSERT INTO BIMESTRE
(ID_BIMESTRE, NUMERO, ANO_LETIVO)
VALUES
(SEQ_BIMESTRE.NEXTVAL, 3, 2026);

INSERT INTO BIMESTRE
(ID_BIMESTRE, NUMERO, ANO_LETIVO)
VALUES
(SEQ_BIMESTRE.NEXTVAL, 4, 2026);


-- ============================================
-- ALUNOS
-- ============================================

INSERT INTO ALUNO
(ID_ALUNO, NOME, DATA_NASCIMENTO, EMAIL, ID_TURMA)
VALUES
(SEQ_ALUNO.NEXTVAL, 'João Silva', DATE '2014-03-15',
 'joao.silva@email.com', 1);

INSERT INTO ALUNO
(ID_ALUNO, NOME, DATA_NASCIMENTO, EMAIL, ID_TURMA)
VALUES
(SEQ_ALUNO.NEXTVAL, 'Maria Santos', DATE '2014-07-22',
 'maria.santos@email.com', 1);

INSERT INTO ALUNO
(ID_ALUNO, NOME, DATA_NASCIMENTO, EMAIL, ID_TURMA)
VALUES
(SEQ_ALUNO.NEXTVAL, 'Pedro Oliveira', DATE '2014-01-10',
 'pedro.oliveira@email.com', 1);

INSERT INTO ALUNO
(ID_ALUNO, NOME, DATA_NASCIMENTO, EMAIL, ID_TURMA)
VALUES
(SEQ_ALUNO.NEXTVAL, 'Ana Costa', DATE '2014-11-05',
 'ana.costa@email.com', 2);

INSERT INTO ALUNO
(ID_ALUNO, NOME, DATA_NASCIMENTO, EMAIL, ID_TURMA)
VALUES
(SEQ_ALUNO.NEXTVAL, 'Lucas Pereira', DATE '2014-05-18',
 'lucas.pereira@email.com', 2);

INSERT INTO ALUNO
(ID_ALUNO, NOME, DATA_NASCIMENTO, EMAIL, ID_TURMA)
VALUES
(SEQ_ALUNO.NEXTVAL, 'Gabriel Lima', DATE '2013-09-27',
 'gabriel.lima@email.com', 3);

INSERT INTO ALUNO
(ID_ALUNO, NOME, DATA_NASCIMENTO, EMAIL, ID_TURMA)
VALUES
(SEQ_ALUNO.NEXTVAL, 'Beatriz Souza', DATE '2013-02-14',
 'beatriz.souza@email.com', 3);

INSERT INTO ALUNO
(ID_ALUNO, NOME, DATA_NASCIMENTO, EMAIL, ID_TURMA)
VALUES
(SEQ_ALUNO.NEXTVAL, 'Rafael Mendes', DATE '2012-08-30',
 'rafael.mendes@email.com', 4);

INSERT INTO ALUNO
(ID_ALUNO, NOME, DATA_NASCIMENTO, EMAIL, ID_TURMA)
VALUES
(SEQ_ALUNO.NEXTVAL, 'Laura Martins', DATE '2012-12-12',
 'laura.martins@email.com', 4);

INSERT INTO ALUNO
(ID_ALUNO, NOME, DATA_NASCIMENTO, EMAIL, ID_TURMA)
VALUES
(SEQ_ALUNO.NEXTVAL, 'Felipe Rocha', DATE '2011-06-20',
 'felipe.rocha@email.com', 5);
 
 
 
 -- ============================================
-- ACOMPANHAMENTOS
-- ============================================

INSERT INTO ACOMPANHAMENTO
(ID_ACOMPANHAMENTO, ID_ALUNO, ID_PROFESSOR, ID_DISCIPLINA,
 ID_BIMESTRE, MEDIA, STATUS, OBSERVACAO)
VALUES
(SEQ_ACOMPANHAMENTO.NEXTVAL, 1, 1, 1, 1,
 8.5, 'APROVADO', 'Bom desempenho em Matemática.');

INSERT INTO ACOMPANHAMENTO
(ID_ACOMPANHAMENTO, ID_ALUNO, ID_PROFESSOR, ID_DISCIPLINA,
 ID_BIMESTRE, MEDIA, STATUS, OBSERVACAO)
VALUES
(SEQ_ACOMPANHAMENTO.NEXTVAL, 1, 2, 2, 1,
 7.5, 'APROVADO', 'Bom desempenho em Português.');

INSERT INTO ACOMPANHAMENTO
(ID_ACOMPANHAMENTO, ID_ALUNO, ID_PROFESSOR, ID_DISCIPLINA,
 ID_BIMESTRE, MEDIA, STATUS, OBSERVACAO)
VALUES
(SEQ_ACOMPANHAMENTO.NEXTVAL, 1, 1, 1, 2,
 9.0, 'APROVADO', 'Evolução no segundo bimestre.');

INSERT INTO ACOMPANHAMENTO
(ID_ACOMPANHAMENTO, ID_ALUNO, ID_PROFESSOR, ID_DISCIPLINA,
 ID_BIMESTRE, MEDIA, STATUS, OBSERVACAO)
VALUES
(SEQ_ACOMPANHAMENTO.NEXTVAL, 2, 1, 1, 1,
 6.5, 'RECUPERACAO', 'Necessita reforço em alguns conteúdos.');

INSERT INTO ACOMPANHAMENTO
(ID_ACOMPANHAMENTO, ID_ALUNO, ID_PROFESSOR, ID_DISCIPLINA,
 ID_BIMESTRE, MEDIA, STATUS, OBSERVACAO)
VALUES
(SEQ_ACOMPANHAMENTO.NEXTVAL, 2, 2, 2, 1,
 8.0, 'APROVADO', 'Bom desempenho.');

INSERT INTO ACOMPANHAMENTO
(ID_ACOMPANHAMENTO, ID_ALUNO, ID_PROFESSOR, ID_DISCIPLINA,
 ID_BIMESTRE, MEDIA, STATUS, OBSERVACAO)
VALUES
(SEQ_ACOMPANHAMENTO.NEXTVAL, 3, 3, 3, 1,
 7.5, 'APROVADO', 'Participação satisfatória.');

INSERT INTO ACOMPANHAMENTO
(ID_ACOMPANHAMENTO, ID_ALUNO, ID_PROFESSOR, ID_DISCIPLINA,
 ID_BIMESTRE, MEDIA, STATUS, OBSERVACAO)
VALUES
(SEQ_ACOMPANHAMENTO.NEXTVAL, 4, 1, 1, 1,
 9.5, 'APROVADO', 'Excelente desempenho.');

INSERT INTO ACOMPANHAMENTO
(ID_ACOMPANHAMENTO, ID_ALUNO, ID_PROFESSOR, ID_DISCIPLINA,
 ID_BIMESTRE, MEDIA, STATUS, OBSERVACAO)
VALUES
(SEQ_ACOMPANHAMENTO.NEXTVAL, 5, 2, 2, 1,
 5.5, 'RECUPERACAO', 'Apresenta dificuldades na disciplina.');

INSERT INTO ACOMPANHAMENTO
(ID_ACOMPANHAMENTO, ID_ALUNO, ID_PROFESSOR, ID_DISCIPLINA,
 ID_BIMESTRE, MEDIA, STATUS, OBSERVACAO)
VALUES
(SEQ_ACOMPANHAMENTO.NEXTVAL, 6, 1, 1, 1,
 8.0, 'APROVADO', 'Bom desempenho.');

INSERT INTO ACOMPANHAMENTO
(ID_ACOMPANHAMENTO, ID_ALUNO, ID_PROFESSOR, ID_DISCIPLINA,
 ID_BIMESTRE, MEDIA, STATUS, OBSERVACAO)
VALUES
(SEQ_ACOMPANHAMENTO.NEXTVAL, 7, 4, 4, 1,
 7.0, 'APROVADO', 'Bom aproveitamento.');

INSERT INTO ACOMPANHAMENTO
(ID_ACOMPANHAMENTO, ID_ALUNO, ID_PROFESSOR, ID_DISCIPLINA,
 ID_BIMESTRE, MEDIA, STATUS, OBSERVACAO)
VALUES
(SEQ_ACOMPANHAMENTO.NEXTVAL, 8, 3, 3, 1,
 6.0, 'RECUPERACAO', 'Precisa melhorar o desempenho.');

INSERT INTO ACOMPANHAMENTO
(ID_ACOMPANHAMENTO, ID_ALUNO, ID_PROFESSOR, ID_DISCIPLINA,
 ID_BIMESTRE, MEDIA, STATUS, OBSERVACAO)
VALUES
(SEQ_ACOMPANHAMENTO.NEXTVAL, 9, 5, 5, 1,
 8.5, 'APROVADO', 'Excelente participação.');

INSERT INTO ACOMPANHAMENTO
(ID_ACOMPANHAMENTO, ID_ALUNO, ID_PROFESSOR, ID_DISCIPLINA,
 ID_BIMESTRE, MEDIA, STATUS, OBSERVACAO)
VALUES
(SEQ_ACOMPANHAMENTO.NEXTVAL, 10, 1, 1, 1,
 9.0, 'APROVADO', 'Ótimo desempenho.');
 
 COMMIT;


-- CONSULTAS

SELECT *
FROM ALUNO
WHERE NOME LIKE '%João%';


SELECT *
FROM ALUNO
WHERE ID_TURMA = 1;


SELECT *
FROM ACOMPANHAMENTO
WHERE ID_ALUNO = 1;


SELECT *
FROM ACOMPANHAMENTO
WHERE ID_DISCIPLINA = 1;


SELECT *
FROM ACOMPANHAMENTO
WHERE STATUS = 'RECUPERACAO';


SELECT *
FROM ACOMPANHAMENTO
WHERE ID_BIMESTRE = 1;





-- ÍNDICE NA TABELA TURMA

CREATE INDEX IDX_TURMA_NOME
ON TURMA(NOME);

-- ÍNDICE NA TABELA PROFESSOR
CREATE INDEX IDX_PROFESSOR_NOME
ON PROFESSOR(NOME);

-- ÍNDICE NA TABELA DISCIPLINA
CREATE INDEX IDX_DISCIPLINA_NOME
ON DISCIPLINA(NOME);

-- ÍNDICE NA TABELA BIMESTRE
CREATE INDEX IDX_BIMESTRE_NUMERO
ON BIMESTRE(NUMERO);

-- ÍNDICE NA TABELA ALUNO
CREATE INDEX IDX_ALUNO_NOME
ON ALUNO(NOME);

-- ÍNDICE NA TABELA ACOMPANHAMENTO
CREATE INDEX IDX_ACOMPANHAMENTO_STATUS
ON ACOMPANHAMENTO(STATUS);


--VIEWS
CREATE VIEW VW_DESEMPENHO_ALUNOS AS
SELECT
    ID_ALUNO,
    ID_DISCIPLINA,
    ID_BIMESTRE,
    MEDIA,
    STATUS
FROM ACOMPANHAMENTO;



SELECT *
FROM VW_DESEMPENHO_ALUNOS;